name: Test Automation WorkFlow

on:
  schedule:
    - cron: "00 18 * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Ensure Logs and Screenshots Folders Exist
      run: |
        mkdir -p logs screenshots
    
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=false
     
    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Logs - ${{ github.run_id }}
        path: logs/

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Screenshots - ${{ github.run_id }}
        path: screenshots/

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: HTML Report - ${{ github.run_id }}
        path: report.html
       
    - name: Test Execution Status
      if: always()
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
      if: always()
      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l public/extent-reports/

    - name: Deploy Report to GitHub Pages
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/
        token: ${{ secrets.PAT2024 }}
        clean: true
